In [1]:
import numpy as np

In [10]:
x = -2 * np.random.rand(100,2)

In [25]:
x[0:8,0]

array([-1.98186892, -0.45136222, -1.15177445, -0.47009601, -0.78751935,
       -1.93228791, -1.38711419, -0.91739632])

In [22]:
a = np.array([1,2])
a = a.reshape(1,-1)

In [23]:
a

array([[1, 2]])

In [30]:
b = np.array([[1,2],[3,4],[2,3]])

In [51]:
b[,0]

array([1])

In [12]:
d_o_d = {"names":{1:'gyan',2:'deepesh',3:'tushar'},
        'class':{1:"cse",2:'ece',3:'mechanical'}}

In [16]:
d_o_d['class'][3]

'mechanical'

In [45]:
f = [[1,3,4,5,5,6],[9,8,7]]

In [55]:
f[:][:int(len(f[0])*0.9)]

[[1, 3, 4, 5, 5, 6], [9, 8, 7]]